### ISSUE TITLE
xorg-server crash

### ISSUE THREAD

**Issue by mmonaco** [xwiimote/xf86-input-xwiimote#1]
Hey David,

I just give this a spin and it immediately crashes my xorg-server when the wiimote is connected. I see the wiimote input class handled 3 times in the log (for each event) and then the whole thing comes down. I don't have debugging symbols right now in my xorg-server, but I'll recompile if this remains a mystery. I have xorg-server 1.12.0

EDIT: Not crashing, just exiting...

EDIT2: symbol lookup error in xwiimote_drv.so: xstrcasecmp, hmm....

**Comment by mmonaco** [comment]
I fixed this with "#undef strcasecmp" just after the headers. Apparently one of the x headers is renaming this to xstrcasecmp, I dont' know what the point is...

**Comment by dvdhrm** [comment]
That is weird. Could you check /usr/include/xorg/xorg-server.h for the HAVE_STRCASECMP line? It should be 1 right? I have pushed a fix moving the xorg-server.h include to the top. Does that fix your issues?

The xserver installs its config.h header as xorg-server.h system-wide, which is really ugly to deal with. If this doesn't fix your issue, try adding "#define HAVE_STRCASECMP 1" to the top of the file.

Thanks
David

**Comment by mmonaco** [comment]
Moving the header to the top does the trick (xserver 1.12.1 RC1)
