### ISSUE TITLE
No mouse Cursor visible

### ISSUE THREAD

**Issue by anduchs** [xwiimote/xf86-input-xwiimote#11]
For some reason, the mouse cursor just turned invisible during the switch from gdm to actual gnome-session (Ubuntu 13.10).

Could this be related to the driver ?

I was thinking about how touchscreens and other inputs differentiate. Maybe it has something to do with that.

**Comment by dvdhrm** [comment]
Cursor handling is left to the X-Server. The drivers have nothing to do with that, so no, very unlikely to be related to xf86-input-xwiimote.

**Comment by anduchs** [comment]
Hmmm... Hasn't occured since... Maybe just some glitch...
If someone (or myself) get's this reproducible I guess we could reopen this bug.
