### ISSUE TITLE
Keymap Controls for Wiimote

### ISSUE THREAD

**Issue by Enverex** [xwiimote/xf86-input-xwiimote#17]
As it stands, the default keys aren't that useful and the Wiimote tools right now don't compile because they need Bluez4 (and I'm on Bluez5).

Is there any chance you could add Options to the xorg driver to let us select options at that point? This would avoid the need for a secondary program to keep running as well.

For reference, what I'm trying to do right now is use the Wiimote as a lightgun in MAME. It sees the IR as a mouse which is fine, but the buttons A and B are detected as "Keyboard Enter + Joystick Start" and "Keyboard Space" which causes all sorts of issues.

**Comment by dvdhrm** [comment]
Please read the xorg-xwiimote man-page as provided by the package. All the options you want are already there.

**Comment by Enverex** [comment]
Not sure how I missed that! Sorry.
