### ISSUE TITLE
no video output or keyboard/mouse input when loading driver

### ISSUE THREAD

**Issue by zachasme** [xwiimote/xf86-input-xwiimote#4]
Hi David,

The xwiimote device driver works very well.

But when using this Xorg input driver, with a Wiimote connected, the video signal is lost and my keyboard becomes unresponsive (ie I cannot switch tty, or terminate X with ctrl+alt+backspace).

If i comment `Driver "xwiimote"`, however, the xorg-server starts without problem.

The last line in my Xorg.0.log is simply that it is loading the xwiimote input driver.

This was on a machine running Arch Linux. I also tried on a different computer, with a fresh Arch Linux installation, but with the same result.

**Comment by dvdhrm** [comment]
Umm, seems like they changed the ABI again. Without a backtrace I cannot really tell, though. Anyway, did you try using the xwiikeymap tool (in xwiimote/tools repository) instead?
